apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: mefasoftdev-alvas
  labels:
    app: mysql
    tier: backend
spec:
  ports:
  - name: mysql
    port: 3306
  clusterIP: None
  selector:
    app: mysql
    tier: backend
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-read
  namespace: mefasoftdev-alvas
  labels:
    app: mysql
    tier: backend
spec:
  ports:
  - name: mysql
    port: 3306
  selector:
    app: mysql
    tier: backend