apiVersion: v1
kind: Service
metadata:
  name: php
  namespace: mefasoftdev-alvas
  labels:
    app: php
    tier: backend
spec:
  selector:
    app: php
    tier: backend
  ports:
  - protocol: TCP
    port: 9000
---    