apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: mefasoftdev-alvas
  labels:
    app: nginx
    tier: backend
spec:
  type: LoadBalancer
  selector:
    app: nginx
    tier: backend
  ports:
  - protocol: TCP
    name: http
    port: 80
  - protocol: TCP
    name: https
    port: 443

  