apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql
  namespace: mefasoftdev-alvas
spec:
  selector:
    matchLabels:
      app: mysql
      tier: backend
  serviceName: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
        tier: backend
    spec:
      serviceAccountName: mysql
      securityContext:
        runAsUser: 0
        fsGroup: 999
      containers:
      - name: mysql
        image: mysql:5.7
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "1"
        ports:
        - name: mysql
          containerPort: 3306
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
          subPath: mysql
        - name: conf
          mountPath: /etc/mysql/mysql.conf.d
        # resources:
        #   requests:
        #     cpu: 500m
        #     memory: 1Gi
      volumes:
      - name: conf
        configMap:
          name: mysql
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        tier: backend
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: hostpath  
      resources:
        requests:
          storage: 5Gi