apiVersion: v1
kind: Pod
metadata:
  name: client-mysql
  namespace: mefasoftdev-alvas
  labels:
    app: mysql
    tier: backend
spec:
  containers:
    - name: mysql-client
      image: mysql:5.7
      command: ["/bin/sh"]
      args:
        - "-c"
        - "while true; do sleep 3600; done"