apiVersion: v1
kind: Service
metadata:
  name: loadbalance
  namespace: mefasoftdev-alvas
spec:
  selector:
    app: app
    tier: backend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer