apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: mefasoftdev-alvas
  labels:
    app: mysql
    tier: backend
data:
  mysqld.cnf: |
    [mysqld]
    pid-file = /var/run/mysqld/mysqld.pid
    #socket = /var/run/mysqld/mysqld.sock
    datadir = /var/lib/mysql
    bind-address = 0.0.0.0
    symbolic-links=0